---
name: "Terraform Checks"

on:
  pull_request:
    paths-ignore:
      - ".github/**"

jobs:
  required-pr-checks:
    name: Required PR Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.x
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3

      - name: TFLint Version
        run: tflint --version

      - name: Cache plugin dir
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: TFLint Init
        run: tflint --init

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -diff -recursive

      - name: Run TFLint
        run: tflint -f compact
