---
name: Github Action Checks
permissions:
  contents: read
  packages: read
  checks: read
on:
  pull_request:
    paths:
      - ".github/**"
jobs:
  required-pr-checks:
    runs-on: ubuntu-latest
    name: Required PR Checks
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl -S -s https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
